app:
  auth:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
    accessExpired: 12312312
    refreshExpired: 23131231313

server:
  port: 8080

spring:
  batch:
    job:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: fitdo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fitdo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dlwovy135!#%

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always