app:
  auth:
    secret: ${AUTH_SECRET}
    accessExpired: ${ACCESSTOKEN_EXPIRED_TIME}
    refreshExpired: ${REFRESHTOKEN_EXPIRED_TIME}

server:
  port: ${PORT}

spring:
  application:
    name: fitdo
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${DB_DDL_TYPE}        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력