version: '3'
services:
  fitdo-web:
    container_name: fitdo-web
    image: jaepyo99/fitdo-web
    env_file:
      - ./.env
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true
    environment:
      - TZ=Asia/Seoul
#  dev:
#    container_name: dev
#    image: jaepyo99/fitdo
#    env_file:
#      - ./.env
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    tty: true
#    environment:
#      - TZ=Asia/Seoul
