--- #local
spring:
  profiles:
    group:
      local:
        - batch
        - redis-local
        - mysql-local
      dev:
        - batch
        - redis-dev
        - mysql-dev
      default:
        - redis-default
        - mysql-default
        - batch
