ext {
    set('springCloudVersion', "2023.0.4")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
dependencies {
    implementation project(":fitdo-mysql")
    implementation project(":fitdo-redis")
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    //spring batch(fitdo-batch)
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation 'com.amazonaws.serverless:aws-serverless-java-container-springboot3:2.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    testImplementation 'org.springframework.batch:spring-batch-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    enabled = true
}
jar {
    enabled = false
}