app:
  auth:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
    accessExpired: 12312312
    refreshExpired: 23131231313
deeplink:
  key: asdasdasdasdaasdasdasdadadasdasa
