spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitdo?serverTimezone=Asia/Seoul
    username: root
    password: vltenfhzjf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never